# Generated by Django 6.0.6 on 2026-06-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='اسم الخدمة')),
                ('link', models.CharField(max_length=200, verbose_name='الرابط')),
                ('icon', models.CharField(max_length=50, verbose_name='الأيقونة (Emoji)')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='اسم الإعداد')),
                ('value', models.TextField(verbose_name='القيمة أو المحتوى')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='وصف')),
            ],
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
